### ISSUE TITLE
Check if an object that's stringified will be truncated?

### ISSUE THREAD

**Issue by Cobertos** [BridgeAR/safe-stable-stringify#31] opened 2022-07-20 05:28 UTC
Is there any way to determine if an object stringified with `stringify.configure(options)` was truncated? Haven't thought of any obvious solution except maybe testing the output string for `"not stringified"`

**Comment by BridgeAR** [comment] 2022-09-15 21:08
The issue is that there is a single result. As such, there's no way to determine that. It would be possible to emit a warning when this happens but this would not be possible to relate properly to the call. I recommend not to use the option in case you would rather not truncate the output.

**Comment by BridgeAR** [comment] 2022-10-18 11:40
I am going to close this as there's no real solution to this besides not using the option in the first place.

**Closed by BridgeAR** 2022-10-18 11:40 UTC
